### ISSUE TITLE
WSOD when module is enabled

### ISSUE THREAD

**Issue by froboy** [palantirnet/workbench_tabs#4]
Brand new site (tested on D8.2 and 8.3), new subtheme of stable with basically nothing in it, got the following on enabling the module:

```
AH01071: Got error 'PHP message: Error: Cannot use string offset as an array in /var/www/ama-d8.local/web/modules/contrib/workbench_tabs/src/Element/LocalTasks.php on line 59 #0 [internal function]: Drupal\\workbench_tabs\\Element\\LocalTasks::preRenderLocalTasks(Array)
...
```

Commenting out that line `$element[$key][$tab_key]['#theme'] = 'workbench_tabs_menu_local_task';` makes the site load again.

Dumping out $element before that gives the following:

```array:6 [▼
  "#type" => "workbench_tabs_local_tasks"
  "#pre_render" => array:1 [▶]
  "#theme" => "workbench_tabs_menu_local_tasks"
  "#primary" => "A"
  "#secondary" => ""
  "#defaults_loaded" => true
]
```
for some elements, and somehow `$elements[#primary]` is getting a string "A" instead of being empty, which is causing the exception when the string is trying to be overridden by an array. 

Adding 
```
        if (!is_array($element[$key])) {
          $element[$key] = [];
        }
```
fixes things up, but I'm not sure if that's a solution to why there's that random "A" in there in the first place...

**Comment by agentrickard** [comment]
I think this is a PHP 7 issue.
